name: Tourism Project Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  register-dataset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies (minimal)
        run: |
          python -m pip install --upgrade pip
          pip install huggingface_hub==0.32.6 fsspec==2024.6.1 pandas==2.2.2

      # (Optional) show workspace to debug paths
      - name: Debug workspace
        run: |
          pwd
          ls -la
          echo "--- find ---"
          find . -maxdepth 3 -type f | sed 's|^\./||'

      - name: Upload Dataset to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python - <<'PY'
          import os
          from huggingface_hub import HfApi, create_repo
          from huggingface_hub.utils import RepositoryNotFoundError

          REPO_ID = "Ansh91/tourism"   # DATASET repo
          LOCAL   = "tourism.csv"      # <-- CSV is at repo root

          api = HfApi(token=os.environ["HF_TOKEN"])

          # Ensure dataset repo exists
          try:
              api.repo_info(repo_id=REPO_ID, repo_type="dataset")
              print(f"Dataset repo '{REPO_ID}' exists.")
          except RepositoryNotFoundError:
              print(f"Creating dataset repo '{REPO_ID}'...")
              create_repo(repo_id=REPO_ID, repo_type="dataset", private=False, token=os.environ["HF_TOKEN"])

          # Skip upload if already present
          files = set(api.list_repo_files(repo_id=REPO_ID, repo_type="dataset"))
          if "tourism.csv" in files:
              print("tourism.csv already present in dataset repo — skipping upload.")
          else:
              if not os.path.exists(LOCAL):
                  raise SystemExit(f"❌ Missing local file: {LOCAL}")
              api.upload_file(
                  path_or_fileobj=LOCAL,
                  path_in_repo="tourism.csv",
                  repo_id=REPO_ID,
                  repo_type="dataset",
              )
              print("✅ Uploaded tourism.csv to dataset repo.")
          PY

  data-prep:
    needs: register-dataset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies (prep)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Data Preparation (splits & upload Xtrain/Xtest/ytrain/ytest)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python model_building/prep.py

  model-traning:
    needs: data-prep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies (train + mlflow)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start MLflow Server (background)
        run: |
          nohup mlflow ui --host 0.0.0.0 --port 5000 &>/dev/null &
          sleep 5

      - name: Model Building (train & upload model to HF model repo)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          MLFLOW_TRACKING_URI: http://127.0.0.1:5000
          MLFLOW_EXPERIMENT_NAME: tourism-wellness-package
          HF_MODEL_REPO: Ansh91/tourism
        run: |
          python model_building/train.py

  deploy-hosting:
    needs: [model-traning, data-prep, register-dataset]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies (hosting)
        run: |
          python -m pip install --upgrade pip
          pip install huggingface_hub==0.32.6

      - name: Push deployment files to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python hosting/hosting.py

